/**
 * AI for Real Life - compact curriculum (6 modules / 28 lessons).
 * Content bodies live in src/lib/aiAtWorkLessonContent/.
 */

export const aiAtWorkCurriculum = {
	courseId: 'ai-at-work',
	title: 'AI for Real Life',
	modules: [
		{
			moduleId: 'module-00',
			order: 1,
			title: 'How generative models actually work',
			tagline: 'Under the hood & tools',
			description:
				'What generative models do, what they do not, and how to pick a tool you can trust for the job.',
			duration: { weeks: 1, lessons: 4 },
			learningOutcomes: [
				'Explain what a model is generating from',
				'Spot common failure modes before they cost you',
				'Choose a chat or media tool for a real task',
			],
			lessons: [
				{
					lessonId: 'ai-lesson-00-1',
					order: 1,
					title: 'Welcome to AI for Real Life',
					learningObjectives: [
						'See how the course is structured',
						'Set up a free AI chat account you will reuse',
						'Run your first structured brief',
					],
					estimatedTime: 45,
					prerequisites: [],
				},
				{
					lessonId: 'ai-lesson-00-2',
					order: 2,
					title: 'What generative models actually do',
					learningObjectives: [
						'Describe prediction vs search vs memory',
						'Separate training data from your chat context',
						'Name three things models are bad at',
					],
					estimatedTime: 50,
					prerequisites: ['ai-lesson-00-1'],
				},
				{
					lessonId: 'ai-lesson-00-3',
					order: 3,
					title: 'Hallucinations, bias, and quiet failure modes',
					learningObjectives: [
						'Recognize confident wrong answers',
						'Add a verification step to any workflow',
						'Spot when a model is inventing sources',
					],
					estimatedTime: 50,
					prerequisites: ['ai-lesson-00-2'],
				},
				{
					lessonId: 'ai-lesson-00-4',
					order: 4,
					title: 'Pick your toolkit',
					learningObjectives: [
						'Compare chat, image, and video tools at a high level',
						'Decide free vs paid for your use case',
						'Document a personal stack you will stick to',
					],
					estimatedTime: 45,
					prerequisites: ['ai-lesson-00-3'],
					isCheckpoint: true,
				},
			],
		},
		{
			moduleId: 'module-01',
			order: 2,
			title: 'Prompting as an engineering skill',
			tagline: 'Briefs, RTCF & iteration',
			description:
				'Treat prompts like briefs: role, task, constraints, examples, and iteration.',
			duration: { weeks: 1, lessons: 5 },
			learningOutcomes: [
				'Write prompts that hold up under reuse',
				'Iterate without starting from scratch each time',
				'Build a small personal prompt library',
			],
			lessons: [
				{
					lessonId: 'ai-lesson-01-1',
					order: 1,
					title: 'Briefs, not vibes',
					learningObjectives: [
						'Turn a vague ask into a reusable brief',
						'Name the four parts of a solid prompt',
						'Rewrite one weak prompt into a strong one',
					],
					estimatedTime: 55,
					prerequisites: ['ai-lesson-00-4'],
				},
				{
					lessonId: 'ai-lesson-01-2',
					order: 2,
					title: 'Role, task, constraints, format',
					learningObjectives: [
						'Assign a useful role without cosplay',
						'Lock output format so results are usable',
						'Add constraints that prevent fluff',
					],
					estimatedTime: 55,
					prerequisites: ['ai-lesson-01-1'],
				},
				{
					lessonId: 'ai-lesson-01-3',
					order: 3,
					title: 'Examples that teach the model',
					learningObjectives: [
						'Use one or two examples instead of long lectures',
						'Show good vs bad when the difference matters',
						'Keep examples short enough to reuse',
					],
					estimatedTime: 55,
					prerequisites: ['ai-lesson-01-2'],
				},
				{
					lessonId: 'ai-lesson-01-4',
					order: 4,
					title: 'Iterate like an engineer',
					learningObjectives: [
						'Change one variable per retry',
						'Keep a short revision log',
						'Know when to stop iterating',
					],
					estimatedTime: 50,
					prerequisites: ['ai-lesson-01-3'],
				},
				{
					lessonId: 'ai-lesson-01-5',
					order: 5,
					title: 'Your prompt library',
					learningObjectives: [
						'Save templates with placeholders',
						'Tag prompts by job (school, work, content)',
						'Version a prompt after it fails in the wild',
					],
					estimatedTime: 50,
					prerequisites: ['ai-lesson-01-4'],
					isCheckpoint: true,
				},
			],
		},
		{
			moduleId: 'module-02',
			order: 3,
			title: 'Generating images and video',
			tagline: 'Style, motion & rights',
			description:
				'Produce media you can actually use - on-brief, editable, and legal to ship.',
			duration: { weeks: 2, lessons: 5 },
			learningOutcomes: [
				'Write image prompts that match a creative brief',
				'Iterate and edit without starting over',
				'Know what you can publish and what you cannot',
			],
			lessons: [
				{
					lessonId: 'ai-lesson-02-1',
					order: 1,
					title: 'Images that survive the brief',
					learningObjectives: [
						'Translate a brief into subject, style, and shot',
						'Generate three usable options, not thirty random ones',
						'Score outputs against the brief',
					],
					estimatedTime: 60,
					prerequisites: ['ai-lesson-01-5'],
				},
				{
					lessonId: 'ai-lesson-02-2',
					order: 2,
					title: 'Style, composition, and reference',
					learningObjectives: [
						'Control composition with camera language',
						'Use references without copying a brand',
						'Keep a consistent look across a set',
					],
					estimatedTime: 60,
					prerequisites: ['ai-lesson-02-1'],
				},
				{
					lessonId: 'ai-lesson-02-3',
					order: 3,
					title: 'Edit, vary, and fix',
					learningObjectives: [
						'Use variations and local edits instead of full regenerations',
						'Fix hands, text, and other common artifacts',
						'Export at the size your channel needs',
					],
					estimatedTime: 55,
					prerequisites: ['ai-lesson-02-2'],
				},
				{
					lessonId: 'ai-lesson-02-4',
					order: 4,
					title: 'Short video and motion basics',
					learningObjectives: [
						'Brief a short clip from a still or script',
						'Keep motion simple enough to control',
						'Plan audio and text overlays separately',
					],
					estimatedTime: 60,
					prerequisites: ['ai-lesson-02-3'],
				},
				{
					lessonId: 'ai-lesson-02-5',
					order: 5,
					title: 'Rights, watermarks, and what you can ship',
					learningObjectives: [
						'Read a tool’s commercial-use rules at a glance',
						'Avoid trademark and likeness traps',
						'Decide when to disclose AI-generated media',
					],
					estimatedTime: 45,
					prerequisites: ['ai-lesson-02-4'],
					isCheckpoint: true,
				},
			],
		},
		{
			moduleId: 'module-03',
			order: 4,
			title: 'Writing that still sounds human',
			tagline: 'Cut, voice & facts',
			description:
				'Use AI for drafts and structure - keep your voice, facts, and integrity.',
			duration: { weeks: 1, lessons: 5 },
			learningOutcomes: [
				'Produce drafts that do not sound like a chatbot',
				'Use AI honestly for school and work',
				'Fact-check before anything leaves your desk',
			],
			lessons: [
				{
					lessonId: 'ai-lesson-03-1',
					order: 1,
					title: 'Drafts without the robot voice',
					learningObjectives: [
						'Brief for voice, audience, and length',
						'Strip AI tells from a draft',
						'Keep a personal voice bank',
					],
					estimatedTime: 55,
					prerequisites: ['ai-lesson-02-5'],
				},
				{
					lessonId: 'ai-lesson-03-2',
					order: 2,
					title: 'The edit pass: cut, voice, facts',
					learningObjectives: [
						'Run a three-pass edit every time',
						'Cut filler without losing meaning',
						'Mark claims that need a source',
					],
					estimatedTime: 55,
					prerequisites: ['ai-lesson-03-1'],
				},
				{
					lessonId: 'ai-lesson-03-3',
					order: 3,
					title: 'School: study plans, notes, and honest help',
					learningObjectives: [
						'Use AI as a tutor, not a ghostwriter',
						'Build a study plan and quiz yourself',
						'Follow academic integrity rules',
					],
					estimatedTime: 50,
					prerequisites: ['ai-lesson-03-2'],
				},
				{
					lessonId: 'ai-lesson-03-4',
					order: 4,
					title: 'Work: email, docs, and meeting notes',
					learningObjectives: [
						'Turn messy notes into a clean summary',
						'Write professional email without corporate sludge',
						'Protect confidential info in prompts',
					],
					estimatedTime: 55,
					prerequisites: ['ai-lesson-03-3'],
				},
				{
					lessonId: 'ai-lesson-03-5',
					order: 5,
					title: 'Research assistants and source checking',
					learningObjectives: [
						'Ask for sources you can open',
						'Cross-check claims in two places',
						'Build a citation habit for public work',
					],
					estimatedTime: 55,
					prerequisites: ['ai-lesson-03-4'],
					isCheckpoint: true,
				},
			],
		},
		{
			moduleId: 'module-04',
			order: 5,
			title: 'A weekly content system',
			tagline: 'Pipeline & batch sprint',
			description:
				'Batch ideas, reuse formats, and run a content week you can actually keep.',
			duration: { weeks: 2, lessons: 5 },
			learningOutcomes: [
				'Design a weekly content pipeline',
				'Repurpose one idea across formats',
				'Hold a quality bar without burning out',
			],
			lessons: [
				{
					lessonId: 'ai-lesson-04-1',
					order: 1,
					title: 'Design your weekly system',
					learningObjectives: [
						'Map inputs → drafts → review → publish',
						'Pick channels you can sustain',
						'Time-box each stage',
					],
					estimatedTime: 55,
					prerequisites: ['ai-lesson-03-5'],
				},
				{
					lessonId: 'ai-lesson-04-2',
					order: 2,
					title: 'Batch ideation and calendars',
					learningObjectives: [
						'Generate a month of angles in one session',
						'Score ideas for effort vs payoff',
						'Fill a simple content calendar',
					],
					estimatedTime: 55,
					prerequisites: ['ai-lesson-04-1'],
				},
				{
					lessonId: 'ai-lesson-04-3',
					order: 3,
					title: 'One idea, many formats',
					learningObjectives: [
						'Turn a core idea into post, thread, and short',
						'Keep the message consistent',
						'Avoid copy-paste sameness',
					],
					estimatedTime: 55,
					prerequisites: ['ai-lesson-04-2'],
				},
				{
					lessonId: 'ai-lesson-04-4',
					order: 4,
					title: 'Quality bar and brand voice',
					learningObjectives: [
						'Write a one-page brand voice sheet',
						'Define a ship / revise / kill checklist',
						'Catch off-brand AI defaults',
					],
					estimatedTime: 50,
					prerequisites: ['ai-lesson-04-3'],
				},
				{
					lessonId: 'ai-lesson-04-5',
					order: 5,
					title: 'Run a one-week content sprint',
					learningObjectives: [
						'Execute seven days of planned content',
						'Log what broke in the system',
						'Adjust the pipeline for week two',
					],
					estimatedTime: 90,
					prerequisites: ['ai-lesson-04-4'],
					isProject: true,
				},
			],
		},
		{
			moduleId: 'module-05',
			order: 6,
			title: 'Ship it responsibly',
			tagline: 'Ethics, portfolio & capstone',
			description:
				'Ethics, privacy, packaging - then ship a content system you can run for yourself or a client.',
			duration: { weeks: 1, lessons: 4 },
			learningOutcomes: [
				'Handle privacy and disclosure correctly',
				'Know when not to use AI',
				'Package a runnable system as a portfolio piece',
			],
			lessons: [
				{
					lessonId: 'ai-lesson-05-1',
					order: 1,
					title: 'Ethics, privacy, and disclosure',
					learningObjectives: [
						'Decide what never goes into a prompt',
						'Disclose AI use when it matters',
						'Handle other people’s data carefully',
					],
					estimatedTime: 45,
					prerequisites: ['ai-lesson-04-5'],
				},
				{
					lessonId: 'ai-lesson-05-2',
					order: 2,
					title: 'When not to use AI',
					learningObjectives: [
						'List high-stakes tasks that need a human',
						'Spot dependency and skill atrophy risks',
						'Build a personal red-flag list',
					],
					estimatedTime: 40,
					prerequisites: ['ai-lesson-05-1'],
				},
				{
					lessonId: 'ai-lesson-05-3',
					order: 3,
					title: 'Package for a client or portfolio',
					learningObjectives: [
						'Document prompts, calendar, and brand sheet',
						'Show before/after samples',
						'Price or present the system clearly',
					],
					estimatedTime: 55,
					prerequisites: ['ai-lesson-05-2'],
				},
				{
					lessonId: 'ai-lesson-05-4',
					order: 4,
					title: 'Capstone: ship your content system',
					learningObjectives: [
						'Deliver a complete runnable system',
						'Self-score against the course outcomes',
						'Plan your next 30 days of use',
					],
					estimatedTime: 90,
					prerequisites: ['ai-lesson-05-3'],
					isCheckpoint: true,
				},
			],
		},
	],
}
