/**
 * Module descriptions for Roblox v2 — AUTO-GENERATED by scripts/gen-roblox-v2.mjs
 */

export const ROBOX_MODULE_META_UK = {
  "module-01": {
    "tagline": "Studio і Parts",
    "description": "Studio, Explorer, Parts, Properties, Snap — фундамент без скриптів. Артефакт: «Мій перший двір».",
    "learningOutcomes": [
      "Орієнтуватися в Studio та Explorer",
      "Створювати Parts з Anchored/CanCollide",
      "Зібрати двір за чеклістом"
    ],
    "phase": "A"
  },
  "module-02": {
    "tagline": "Solid modeling",
    "description": "Model vs Folder, PrimaryPart, Union/Negate, Decal. Артефакт: будинок з вікнами.",
    "learningOutcomes": [
      "Групувати Parts у Model",
      "Різати отвори Negate+Union",
      "Зібрати House з PrimaryPart"
    ],
    "phase": "A"
  },
  "module-03": {
    "tagline": "Біом і світло",
    "description": "Terrain, Lighting, Sky, ambient-звук. Артефакт: живий біом навколо двору.",
    "learningOutcomes": [
      "Малювати базовий terrain",
      "Налаштувати Lighting/Sky",
      "Додати ambient звук"
    ],
    "phase": "A"
  },
  "module-04": {
    "tagline": "Перше «вау»",
    "description": "Output, шаблони Kill/CP/монети/двері/телепорт/меню. Артефакт: іскровий двір.",
    "learningOutcomes": [
      "Читати Output",
      "Вставляти й кастомізувати шаблони",
      "Зібрати 5+ механік у loop"
    ],
    "phase": "B"
  },
  "module-05": {
    "tagline": "Пишемо самі",
    "description": "local, number/string/boolean, Part через змінну, Vector3. Проєкт: Пульт кольору.",
    "learningOutcomes": [
      "Створювати local змінні",
      "Змінювати Properties з коду",
      "Зібрати Пульт кольору"
    ],
    "phase": "C"
  },
  "module-06": {
    "tagline": "Рішення в коді",
    "description": "Порівняння, if/elseif/else, Touched+умова, прапорці. Проєкт: VIP-двері.",
    "learningOutcomes": [
      "Писати порівняння і if",
      "Фільтрувати Touched",
      "Зробити toggle/VIP логіку"
    ],
    "phase": "C"
  },
  "module-07": {
    "tagline": "Повтори й фабрика",
    "description": "for, while, спавн Parts, таймер, цикл+if. Проєкт: Фабрика блоків.",
    "learningOutcomes": [
      "Писати for і while",
      "Спавнити Parts безпечно",
      "Комбінувати цикл з if"
    ],
    "phase": "C"
  },
  "module-08": {
    "tagline": "Код як інструменти",
    "description": "function, параметри, return, Connect, ModuleScript, tables. Проєкт: інвентар + NPC.",
    "learningOutcomes": [
      "Писати функції з return",
      "Підключати події іменовано",
      "Використовувати таблиці й ModuleScript"
    ],
    "phase": "C"
  },
  "module-09": {
    "tagline": "Рівень своїм кодом",
    "description": "Дизайн маршруту, пастки-системою, CP, movers, фініш, таймер. Здача run.",
    "learningOutcomes": [
      "Зібрати playable obby",
      "Масштабувати пастки функціями",
      "Додати фініш і таймер"
    ],
    "phase": "D"
  },
  "module-10": {
    "tagline": "Прогресія чисел",
    "description": "Збір, Power, магазин, RemoteEvent GUI, мета. Артефакт: міні-симулятор.",
    "learningOutcomes": [
      "Звʼязати збір і Power",
      "Зробити серверні покупки",
      "Збалансувати сесію"
    ],
    "phase": "D"
  },
  "module-11": {
    "tagline": "База і економіка",
    "description": "Plot, dropper, collector, кнопки, апгрейди, rebirth, save lite.",
    "learningOutcomes": [
      "Побудувати drop→collect→cash",
      "Робити покупки на plot",
      "Додати rebirth або save"
    ],
    "phase": "D"
  },
  "module-12": {
    "tagline": "Інструменти в руках",
    "description": "Tool → урон → HP UI + магазин → арена з juice → здача.",
    "learningOutcomes": [
      "Створити Tool з дією",
      "Показати HP у GUI",
      "Продати Tool через whitelist"
    ],
    "phase": "D"
  },
  "module-13": {
    "tagline": "Доводимо до кінця",
    "description": "Пітч, vertical slice, Must, UX, publish+буст lite, freeze+Showcase Day.",
    "learningOutcomes": [
      "Довести гру до v1",
      "Пройти UX-чекліст",
      "Презентувати на Showcase"
    ],
    "phase": "E"
  }
}

export const ROBOX_MODULE_META_EN = {
  "module-01": {
    "tagline": "Studio & Parts",
    "description": "Studio, Explorer, Parts, Properties, Snap — foundations without scripts. Artifact: My First Yard.",
    "learningOutcomes": [
      "Navigate Studio and Explorer",
      "Create Parts with Anchored/CanCollide",
      "Build a yard checklist-ready"
    ],
    "phase": "A"
  },
  "module-02": {
    "tagline": "Solid modeling",
    "description": "Model vs Folder, PrimaryPart, Union/Negate, Decals. Artifact: house with windows.",
    "learningOutcomes": [
      "Group Parts into Models",
      "Cut holes with Negate+Union",
      "Assemble a House with PrimaryPart"
    ],
    "phase": "A"
  },
  "module-03": {
    "tagline": "Biome & lighting",
    "description": "Terrain, Lighting, Sky, ambient sound. Artifact: a living biome around the yard.",
    "learningOutcomes": [
      "Sculpt basic terrain",
      "Tune Lighting/Sky",
      "Add ambient sound"
    ],
    "phase": "A"
  },
  "module-04": {
    "tagline": "First wow",
    "description": "Output, Kill/CP/coins/doors/teleport/menu templates. Artifact: spark yard.",
    "learningOutcomes": [
      "Read the Output",
      "Paste and customize templates",
      "Combine 5+ mechanics into a loop"
    ],
    "phase": "B"
  },
  "module-05": {
    "tagline": "We write it ourselves",
    "description": "local, number/string/boolean, Part via variable, Vector3. Project: Color Console.",
    "learningOutcomes": [
      "Create local variables",
      "Change Properties from code",
      "Build the Color Console"
    ],
    "phase": "C"
  },
  "module-06": {
    "tagline": "Decisions in code",
    "description": "Comparisons, if/elseif/else, Touched+condition, flags. Project: VIP doors.",
    "learningOutcomes": [
      "Write comparisons and if",
      "Filter Touched events",
      "Build toggle/VIP logic"
    ],
    "phase": "C"
  },
  "module-07": {
    "tagline": "Repetition & factory",
    "description": "for, while, Part spawn, timers, loop+if. Project: Brick Factory.",
    "learningOutcomes": [
      "Write for and while",
      "Spawn Parts safely",
      "Combine loops with if"
    ],
    "phase": "C"
  },
  "module-08": {
    "tagline": "Code as tools",
    "description": "function, params, return, Connect, ModuleScript, tables. Project: inventory + NPC.",
    "learningOutcomes": [
      "Write functions with return",
      "Wire named event handlers",
      "Use tables and ModuleScripts"
    ],
    "phase": "C"
  },
  "module-09": {
    "tagline": "Level with your code",
    "description": "Course design, hazard systems, CPs, movers, finish, timer. Submit a full run.",
    "learningOutcomes": [
      "Ship a playable obby",
      "Scale hazards with functions",
      "Add finish and timer"
    ],
    "phase": "D"
  },
  "module-10": {
    "tagline": "Number progression",
    "description": "Collecting, Power, shop, RemoteEvent GUI, goals. Artifact: mini-simulator.",
    "learningOutcomes": [
      "Link collecting and Power",
      "Ship server-side purchases",
      "Balance a session"
    ],
    "phase": "D"
  },
  "module-11": {
    "tagline": "Base & economy",
    "description": "Plot, dropper, collector, buttons, upgrades, rebirth, light save.",
    "learningOutcomes": [
      "Build drop→collect→cash",
      "Run plot purchases",
      "Add rebirth or save"
    ],
    "phase": "D"
  },
  "module-12": {
    "tagline": "Tools in hand",
    "description": "Tool → damage → HP UI + shop → juiced arena → checkpoint.",
    "learningOutcomes": [
      "Create a Tool with an action",
      "Show HP in GUI",
      "Sell Tools via whitelist"
    ],
    "phase": "D"
  },
  "module-13": {
    "tagline": "Ship it",
    "description": "Pitch, vertical slice, Must, UX, publish+boost lite, freeze+Showcase Day.",
    "learningOutcomes": [
      "Ship a v1 game",
      "Pass a UX checklist",
      "Present on Showcase Day"
    ],
    "phase": "E"
  }
}

export const ROBOX_MODULE_TITLE_UK = {
  "module-01": "01 — Робочий стіл будівельника",
  "module-02": "02 — Models, Union і будинок",
  "module-03": "03 — Світ, ландшафт і атмосфера",
  "module-04": "04 — Іскри: готовий код",
  "module-05": "05 — Змінні та типи",
  "module-06": "06 — Умови if / else",
  "module-07": "07 — Цикли",
  "module-08": "08 — Функції, події, таблиці",
  "module-09": "09 — Obby / платформер",
  "module-10": "10 — Симулятор",
  "module-11": "11 — Tycoon",
  "module-12": "12 — Tools і GUI",
  "module-13": "13 — Реліз і Showcase"
}

export const ROBOX_MODULE_TITLE_EN = {
  "module-01": "01 — Builder Desk",
  "module-02": "02 — Models, Unions & House",
  "module-03": "03 — World, Terrain & Atmosphere",
  "module-04": "04 — Sparks: Ready-Made Code",
  "module-05": "05 — Variables and Types",
  "module-06": "06 — Conditionals if / else",
  "module-07": "07 — Loops",
  "module-08": "08 — Functions, Events, Tables",
  "module-09": "09 — Obby / Platformer",
  "module-10": "10 — Simulator",
  "module-11": "11 — Tycoon",
  "module-12": "12 — Tools & GUI",
  "module-13": "13 — Release & Showcase"
}

export const ROBOX_PHASES = [
  {
    "id": "A",
    "titleUk": "Студія і моделі",
    "titleEn": "Studio & Modeling",
    "modules": [
      1,
      2,
      3
    ]
  },
  {
    "id": "B",
    "titleUk": "Іскри з кодом",
    "titleEn": "Sparks & Ready Code",
    "modules": [
      4
    ]
  },
  {
    "id": "C",
    "titleUk": "Серйозний Lua",
    "titleEn": "Serious Lua",
    "modules": [
      5,
      6,
      7,
      8
    ]
  },
  {
    "id": "D",
    "titleUk": "Ігрові механіки",
    "titleEn": "Game Mechanics",
    "modules": [
      9,
      10,
      11,
      12
    ]
  },
  {
    "id": "E",
    "titleUk": "Реліз",
    "titleEn": "Release",
    "modules": [
      13
    ]
  }
]

export function enrichRobloxModules(modules, locale = 'uk') {
  const meta = locale === 'en' ? ROBOX_MODULE_META_EN : ROBOX_MODULE_META_UK
  const titles = locale === 'en' ? ROBOX_MODULE_TITLE_EN : ROBOX_MODULE_TITLE_UK
  return (modules || []).map((mod) => {
    const m = meta[mod.moduleId] || {}
    return {
      ...mod,
      title: titles[mod.moduleId] || mod.title,
      tagline: m.tagline || '',
      description: m.description || mod.description,
      learningOutcomes: m.learningOutcomes || mod.learningOutcomes || [],
      phase: m.phase || null,
    }
  })
}
