/**
 * Roblox Studio v2 — 92 lessons / 13 modules
 * AUTO-GENERATED by scripts/gen-roblox-v2.mjs — do not edit by hand
 */

export const robloxCurriculum = {
  "courseId": "roblox-studio",
  "title": "Roblox Studio: від першої Part до власної гри",
  "modules": [
    {
      "moduleId": "module-01",
      "order": 0,
      "title": "01 — Робочий стіл будівельника",
      "description": "Робочий стіл будівельника",
      "duration": {
        "weeks": 4,
        "lessons": 8
      },
      "learningOutcomes": [],
      "lessons": [
        {
          "lessonId": "lesson-roblox-1-1",
          "order": 1,
          "title": "1.1 — Ласкаво просимо до Studio",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-1-2",
          "order": 2,
          "title": "1.2 — Камера й перша доріжка",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-1-1"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-1-3",
          "order": 3,
          "title": "1.3 — Explorer: порядок у світі",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-1-2"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-1-4",
          "order": 4,
          "title": "1.4 — Part і Properties",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-1-3"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-1-5",
          "order": 5,
          "title": "1.5 — Move, Scale, Rotate + Snap",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-1-4"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-1-6",
          "order": 6,
          "title": "1.6 — Будуємо двір: композиція",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-1-5"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-1-7",
          "order": 7,
          "title": "1.7 — Workspace і Storage",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-1-6"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-1-8",
          "order": 8,
          "title": "1.8 — Чекпоінт: Мій перший двір",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-1-7"
          ],
          "isCheckpoint": true
        }
      ]
    },
    {
      "moduleId": "module-02",
      "order": 1,
      "title": "02 — Models, Union і будинок",
      "description": "Models, Union і будинок",
      "duration": {
        "weeks": 4,
        "lessons": 8
      },
      "learningOutcomes": [],
      "lessons": [
        {
          "lessonId": "lesson-roblox-2-1",
          "order": 1,
          "title": "2.1 — Model чи Folder?",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-1-8"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-2-2",
          "order": 2,
          "title": "2.2 — PrimaryPart",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-2-1"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-2-3",
          "order": 3,
          "title": "2.3 — Union: зливаємо Parts",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-2-2"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-2-4",
          "order": 4,
          "title": "2.4 — NegatePart: вирізаємо вікно",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-2-3"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-2-5",
          "order": 5,
          "title": "2.5 — Separate і ремонт Union",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-2-4"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-2-6",
          "order": 6,
          "title": "2.6 — Pivot і збірка даху",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-2-5"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-2-7",
          "order": 7,
          "title": "2.7 — Decal і фасад",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-2-6"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-2-8",
          "order": 8,
          "title": "2.8 — Чекпоінт: будинок з вікнами",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-2-7"
          ],
          "isCheckpoint": true
        }
      ]
    },
    {
      "moduleId": "module-03",
      "order": 2,
      "title": "03 — Світ, ландшафт і атмосфера",
      "description": "Світ, ландшафт і атмосфера",
      "duration": {
        "weeks": 3,
        "lessons": 6
      },
      "learningOutcomes": [],
      "lessons": [
        {
          "lessonId": "lesson-roblox-3-1",
          "order": 1,
          "title": "3.1 — Terrain Editor: перша земля",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-2-8"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-3-2",
          "order": 2,
          "title": "3.2 — Матеріали ландшафту і біом",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-3-1"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-3-3",
          "order": 3,
          "title": "3.3 — Lighting і Atmosphere",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-3-2"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-3-4",
          "order": 4,
          "title": "3.4 — Sky і листівка локації",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-3-3"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-3-5",
          "order": 5,
          "title": "3.5 — Звук зони",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-3-4"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-3-6",
          "order": 6,
          "title": "3.6 — Чекпоінт: живий світ",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-3-5"
          ],
          "isCheckpoint": true
        }
      ]
    },
    {
      "moduleId": "module-04",
      "order": 3,
      "title": "04 — Іскри: готовий код",
      "description": "Іскри: готовий код",
      "duration": {
        "weeks": 5,
        "lessons": 10
      },
      "learningOutcomes": [],
      "lessons": [
        {
          "lessonId": "lesson-roblox-4-1",
          "order": 1,
          "title": "4.1 — Output, Script і print",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-3-6"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-4-2",
          "order": 2,
          "title": "4.2 — Kill brick (готовий Touched)",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-4-1"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-4-3",
          "order": 3,
          "title": "4.3 — Checkpoint",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-4-2"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-4-4",
          "order": 4,
          "title": "4.4 — Монета і leaderstats",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-4-3"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-4-5",
          "order": 5,
          "title": "4.5 — Двері на ClickDetector",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-4-4"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-4-6",
          "order": 6,
          "title": "4.6 — Телепорт",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-4-5"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-4-7",
          "order": 7,
          "title": "4.7 — Платформа що зникає",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-4-6"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-4-8",
          "order": 8,
          "title": "4.8 — Просте меню ScreenGui",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-4-7"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-4-9",
          "order": 9,
          "title": "4.9 — Збірка: Іскровий двір",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-4-8"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-4-10",
          "order": 10,
          "title": "4.10 — Презентація: жива гра",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-4-9"
          ],
          "isCheckpoint": true
        }
      ]
    },
    {
      "moduleId": "module-05",
      "order": 4,
      "title": "05 — Змінні та типи",
      "description": "Змінні та типи",
      "duration": {
        "weeks": 3,
        "lessons": 6
      },
      "learningOutcomes": [],
      "lessons": [
        {
          "lessonId": "lesson-roblox-5-1",
          "order": 1,
          "title": "5.1 — Що таке змінна",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-4-10"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-5-2",
          "order": 2,
          "title": "5.2 — Типи: number, string, boolean",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-5-1"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-5-3",
          "order": 3,
          "title": "5.3 — Змінна вказує на Part",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-5-2"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-5-4",
          "order": 4,
          "title": "5.4 — Числова логіка і рахунок",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-5-3"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-5-5",
          "order": 5,
          "title": "5.5 — Vector3: розмір і позиція",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-5-4"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-5-6",
          "order": 6,
          "title": "5.6 — Проєкт: Пульт кольору",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-5-5"
          ],
          "isCheckpoint": true
        }
      ]
    },
    {
      "moduleId": "module-06",
      "order": 5,
      "title": "06 — Умови if / else",
      "description": "Умови if / else",
      "duration": {
        "weeks": 3,
        "lessons": 6
      },
      "learningOutcomes": [],
      "lessons": [
        {
          "lessonId": "lesson-roblox-6-1",
          "order": 1,
          "title": "6.1 — Порівняння і boolean",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-5-6"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-6-2",
          "order": 2,
          "title": "6.2 — if then end",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-6-1"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-6-3",
          "order": 3,
          "title": "6.3 — else і elseif",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-6-2"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-6-4",
          "order": 4,
          "title": "6.4 — Touched + if: зони",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-6-3"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-6-5",
          "order": 5,
          "title": "6.5 — Прапорці і ClickDetector",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-6-4"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-6-6",
          "order": 6,
          "title": "6.6 — Проєкт: двері VIP / пароль",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-6-5"
          ],
          "isCheckpoint": true
        }
      ]
    },
    {
      "moduleId": "module-07",
      "order": 6,
      "title": "07 — Цикли",
      "description": "Цикли",
      "duration": {
        "weeks": 3,
        "lessons": 6
      },
      "learningOutcomes": [],
      "lessons": [
        {
          "lessonId": "lesson-roblox-7-1",
          "order": 1,
          "title": "7.1 — Навіщо цикли + for",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-6-6"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-7-2",
          "order": 2,
          "title": "7.2 — for і спавн Part",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-7-1"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-7-3",
          "order": 3,
          "title": "7.3 — while і безпека",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-7-2"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-7-4",
          "order": 4,
          "title": "7.4 — Таймер у грі",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-7-3"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-7-5",
          "order": 5,
          "title": "7.5 — Цикл + if: фільтр",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-7-4"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-7-6",
          "order": 6,
          "title": "7.6 — Проєкт: Фабрика блоків",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-7-5"
          ],
          "isCheckpoint": true
        }
      ]
    },
    {
      "moduleId": "module-08",
      "order": 7,
      "title": "08 — Функції, події, таблиці",
      "description": "Функції, події, таблиці",
      "duration": {
        "weeks": 4,
        "lessons": 8
      },
      "learningOutcomes": [],
      "lessons": [
        {
          "lessonId": "lesson-roblox-8-1",
          "order": 1,
          "title": "8.1 — Що таке функція",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-7-6"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-8-2",
          "order": 2,
          "title": "8.2 — Параметри",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-8-1"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-8-3",
          "order": 3,
          "title": "8.3 — return",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-8-2"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-8-4",
          "order": 4,
          "title": "8.4 — Події: функція як реакція",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-8-3"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-8-5",
          "order": 5,
          "title": "8.5 — ModuleScript intro",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-8-4"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-8-6",
          "order": 6,
          "title": "8.6 — Таблиці: список",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-8-5"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-8-7",
          "order": 7,
          "title": "8.7 — Словник + діалог NPC",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-8-6"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-8-8",
          "order": 8,
          "title": "8.8 — Проєкт: інвентар + NPC",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-8-7"
          ],
          "isCheckpoint": true
        }
      ]
    },
    {
      "moduleId": "module-09",
      "order": 8,
      "title": "09 — Obby / платформер",
      "description": "Obby / платформер",
      "duration": {
        "weeks": 4,
        "lessons": 8
      },
      "learningOutcomes": [],
      "lessons": [
        {
          "lessonId": "lesson-roblox-9-1",
          "order": 1,
          "title": "9.1 — Дизайн маршруту obby",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-8-8"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-9-2",
          "order": 2,
          "title": "9.2 — Пастки функціями",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-9-1"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-9-3",
          "order": 3,
          "title": "9.3 — Чекпоінти системою",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-9-2"
          ],
          "isCheckpoint": true
        },
        {
          "lessonId": "lesson-roblox-9-4",
          "order": 4,
          "title": "9.4 — Рухомі платформи",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-9-3"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-9-5",
          "order": 5,
          "title": "9.5 — Фініш і перемога",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-9-4"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-9-6",
          "order": 6,
          "title": "9.6 — Таймер проходження",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-9-5"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-9-7",
          "order": 7,
          "title": "9.7 — Баланс і polish",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-9-6"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-9-8",
          "order": 8,
          "title": "9.8 — Чекпоінт: презентація Obby",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-9-7"
          ],
          "isCheckpoint": true
        }
      ]
    },
    {
      "moduleId": "module-10",
      "order": 9,
      "title": "10 — Симулятор",
      "description": "Симулятор",
      "duration": {
        "weeks": 3,
        "lessons": 6
      },
      "learningOutcomes": [],
      "lessons": [
        {
          "lessonId": "lesson-roblox-10-1",
          "order": 1,
          "title": "10.1 — Ядро жанру симулятора",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-9-8"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-10-2",
          "order": 2,
          "title": "10.2 — Збір і Power",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-10-1"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-10-3",
          "order": 3,
          "title": "10.3 — Магазин: ціни і canAfford",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-10-2"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-10-4",
          "order": 4,
          "title": "10.4 — UI магазину + RemoteEvent",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-10-3"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-10-5",
          "order": 5,
          "title": "10.5 — Множник і мета",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-10-4"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-10-6",
          "order": 6,
          "title": "10.6 — Чекпоінт: презентація симулятора",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-10-5"
          ],
          "isCheckpoint": true
        }
      ]
    },
    {
      "moduleId": "module-11",
      "order": 10,
      "title": "11 — Tycoon",
      "description": "Tycoon",
      "duration": {
        "weeks": 4,
        "lessons": 8
      },
      "learningOutcomes": [],
      "lessons": [
        {
          "lessonId": "lesson-roblox-11-1",
          "order": 1,
          "title": "11.1 — Plot: моя база",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-10-6"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-11-2",
          "order": 2,
          "title": "11.2 — Dropper",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-11-1"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-11-3",
          "order": 3,
          "title": "11.3 — Collector",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-11-2"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-11-4",
          "order": 4,
          "title": "11.4 — Кнопки покупок",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-11-3"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-11-5",
          "order": 5,
          "title": "11.5 — Апгрейди доходу",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-11-4"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-11-6",
          "order": 6,
          "title": "11.6 — Rebirth lite",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-11-5"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-11-7",
          "order": 7,
          "title": "11.7 — Збереження прогресу",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-11-6"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-11-8",
          "order": 8,
          "title": "11.8 — Чекпоінт: презентація Tycoon",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-11-7"
          ],
          "isCheckpoint": true
        }
      ]
    },
    {
      "moduleId": "module-12",
      "order": 11,
      "title": "12 — Tools і GUI",
      "description": "Tools і GUI",
      "duration": {
        "weeks": 3,
        "lessons": 6
      },
      "learningOutcomes": [],
      "lessons": [
        {
          "lessonId": "lesson-roblox-12-1",
          "order": 1,
          "title": "12.1 — Що таке Tool",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-11-8"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-12-2",
          "order": 2,
          "title": "12.2 — Activated: інструмент діє",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-12-1"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-12-3",
          "order": 3,
          "title": "12.3 — Урон і Humanoid",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-12-2"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-12-4",
          "order": 4,
          "title": "12.4 — GUI HP + магазин Tools",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-12-3"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-12-5",
          "order": 5,
          "title": "12.5 — Збірка арени + juice",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-12-4"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-12-6",
          "order": 6,
          "title": "12.6 — Чекпоінт: презентація Tools",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-12-5"
          ],
          "isCheckpoint": true
        }
      ]
    },
    {
      "moduleId": "module-13",
      "order": 12,
      "title": "13 — Реліз і Showcase",
      "description": "Реліз і Showcase",
      "duration": {
        "weeks": 3,
        "lessons": 6
      },
      "learningOutcomes": [],
      "lessons": [
        {
          "lessonId": "lesson-roblox-13-1",
          "order": 1,
          "title": "13.1 — Пітч і вибір жанру",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-12-6"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-13-2",
          "order": 2,
          "title": "13.2 — Vertical slice",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-13-1"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-13-3",
          "order": 3,
          "title": "13.3 — Must #2 і #3",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-13-2"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-13-4",
          "order": 4,
          "title": "13.4 — Багфікс і UX-прохід",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-13-3"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-13-5",
          "order": 5,
          "title": "13.5 — Publish + GamePass/Badge lite",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-13-4"
          ],
          "isCheckpoint": false
        },
        {
          "lessonId": "lesson-roblox-13-6",
          "order": 6,
          "title": "13.6 — Feature freeze + Showcase Day",
          "learningObjectives": [],
          "estimatedTime": 60,
          "prerequisites": [
            "lesson-roblox-13-5"
          ],
          "isCheckpoint": true
        }
      ]
    }
  ]
}
