/**
 * Unity — 40 lessons / 8 modules
 * Grid: M1×5 + M2×5 + M3×5 + M4×5 + M5×5 + M6×5 + M7×5 + M8×5
 */

export const unityCurriculum = {
  courseId: 'unity-game-development',
  title: 'Unity: 40 уроків — від нуля до готової гри',
  modules: [
    {
      moduleId: 'module-01',
      order: 0,
      title: '01 - Старт у Unity',
      description: 'Unity Hub, редактор, Scene, GameObject, матеріали і світло',
      duration: { weeks: 2, lessons: 5 },
      learningOutcomes: [],
      lessons: [
        {
          lessonId: 'lesson-unity-1-1',
          order: 1,
          title: '1.1 - Unity Hub і перший проєкт',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: [],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-1-2',
          order: 2,
          title: '1.2 - Навігація у Scene: камера, Hierarchy, Inspector',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-1-1'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-1-3',
          order: 3,
          title: '1.3 - GameObject і примітиви: будуємо кімнату',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-1-2'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-1-4',
          order: 4,
          title: '1.4 - Materials, Light, Camera - оживляємо сцену',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-1-3'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-1-5',
          order: 5,
          title: '1.5 - Checkpoint: кімната з освітленням і камерою',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-1-4'],
          isCheckpoint: true,
        },
      ],
    },
    {
      moduleId: 'module-02',
      order: 1,
      title: '02 - C# основи',
      description: 'MonoBehaviour, змінні, SerializeField, if, Input, методи, GetComponent',
      duration: { weeks: 3, lessons: 5 },
      learningOutcomes: [],
      lessons: [
        {
          lessonId: 'lesson-unity-2-1',
          order: 1,
          title: '2.1 - MonoBehaviour: Start і Update',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: [],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-2-2',
          order: 2,
          title: '2.2 - Змінні та SerializeField в Inspector',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-2-1'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-2-3',
          order: 3,
          title: '2.3 - Умови if та Input: керування з клавіатури',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-2-2'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-2-4',
          order: 4,
          title: '2.4 - Методи та GetComponent',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-2-3'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-2-5',
          order: 5,
          title: '2.5 - Checkpoint: керований куб',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-2-4'],
          isCheckpoint: true,
        },
      ],
    },
    {
      moduleId: 'module-03',
      order: 2,
      title: '03 - Фізика',
      description: 'Rigidbody, Colliders, зіткнення й тригери, Prefabs та Instantiate',
      duration: { weeks: 3, lessons: 5 },
      learningOutcomes: [],
      lessons: [
        {
          lessonId: 'lesson-unity-3-1',
          order: 1,
          title: '3.1 - Rigidbody і гравітація',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: [],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-3-2',
          order: 2,
          title: '3.2 - Colliders: тверді й проходні об’єкти',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-3-1'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-3-3',
          order: 3,
          title: '3.3 - OnCollisionEnter та OnTriggerEnter',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-3-2'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-3-4',
          order: 4,
          title: '3.4 - Prefabs та Instantiate',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-3-3'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-3-5',
          order: 5,
          title: '3.5 - Checkpoint: збирач монет',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-3-4'],
          isCheckpoint: true,
        },
      ],
    },
    {
      moduleId: 'module-04',
      order: 3,
      title: '04 - Гравець',
      description: 'Рух персонажа, камера-слідкувач, стрибок і ground check, анімація',
      duration: { weeks: 3, lessons: 5 },
      learningOutcomes: [],
      lessons: [
        {
          lessonId: 'lesson-unity-4-1',
          order: 1,
          title: '4.1 - Рух персонажа (Transform і CharacterController)',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: [],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-4-2',
          order: 2,
          title: '4.2 - Камера, що слідує за гравцем',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-4-1'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-4-3',
          order: 3,
          title: '4.3 - Стрибок і перевірка землі (ground check)',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-4-2'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-4-4',
          order: 4,
          title: '4.4 - Основи анімації: Animator і переходи',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-4-3'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-4-5',
          order: 5,
          title: '4.5 - Checkpoint: персонаж-платформер',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-4-4'],
          isCheckpoint: true,
        },
      ],
    },
    {
      moduleId: 'module-05',
      order: 4,
      title: '05 - UI і цикл гри',
      description: 'Canvas, Text, Button, HUD рахунку, здоров’я, меню паузи й рестарт',
      duration: { weeks: 2, lessons: 5 },
      learningOutcomes: [],
      lessons: [
        {
          lessonId: 'lesson-unity-5-1',
          order: 1,
          title: '5.1 - Canvas, Text, Button',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: [],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-5-2',
          order: 2,
          title: '5.2 - HUD рахунку (score)',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-5-1'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-5-3',
          order: 3,
          title: '5.3 - Здоров’я гравця (health system)',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-5-2'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-5-4',
          order: 4,
          title: '5.4 - Меню паузи і рестарт',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-5-3'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-5-5',
          order: 5,
          title: '5.5 - Checkpoint: гра з повним циклом',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-5-4'],
          isCheckpoint: true,
        },
      ],
    },
    {
      moduleId: 'module-06',
      order: 5,
      title: '06 - Рівень і вороги',
      description: 'Побудова рівня, спавн ворогів, проста AI, звук',
      duration: { weeks: 3, lessons: 5 },
      learningOutcomes: [],
      lessons: [
        {
          lessonId: 'lesson-unity-6-1',
          order: 1,
          title: '6.1 - Побудова рівня (level layout, блокаут)',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: [],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-6-2',
          order: 2,
          title: '6.2 - Спавн ворогів',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-6-1'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-6-3',
          order: 3,
          title: '6.3 - Проста AI: патрулювання по точках (waypoints)',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-6-2'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-6-4',
          order: 4,
          title: '6.4 - Звук: AudioSource і AudioClip',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-6-3'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-6-5',
          order: 5,
          title: '6.5 - Checkpoint: повний рівень',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-6-4'],
          isCheckpoint: true,
        },
      ],
    },
    {
      moduleId: 'module-07',
      order: 6,
      title: '07 - Поліш і білд',
      description: 'Particles, ScriptableObjects, LoadScene, Build Settings',
      duration: { weeks: 2, lessons: 5 },
      learningOutcomes: [],
      lessons: [
        {
          lessonId: 'lesson-unity-7-1',
          order: 1,
          title: '7.1 - Particle System: візуальні ефекти',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: [],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-7-2',
          order: 2,
          title: '7.2 - ScriptableObjects: дані окремо від логіки',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-7-1'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-7-3',
          order: 3,
          title: '7.3 - LoadScene і перехід між рівнями',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-7-2'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-7-4',
          order: 4,
          title: '7.4 - Build Settings і збірка гри',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-7-3'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-7-5',
          order: 5,
          title: '7.5 - Checkpoint: перша збірка (build)',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-7-4'],
          isCheckpoint: true,
        },
      ],
    },
    {
      moduleId: 'module-08',
      order: 7,
      title: '08 - Фінальний проєкт',
      description: 'GDD, core loop, поліш контенту, плейтест і релізне портфоліо',
      duration: { weeks: 2, lessons: 5 },
      learningOutcomes: [],
      lessons: [
        {
          lessonId: 'lesson-unity-8-1',
          order: 1,
          title: '8.1 - GDD: документ дизайну гри',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: [],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-8-2',
          order: 2,
          title: '8.2 - Core loop фінального проєкту',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-8-1'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-8-3',
          order: 3,
          title: '8.3 - Контент і поліш (polish pass)',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-8-2'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-8-4',
          order: 4,
          title: '8.4 - Плейтест і виправлення багів',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-8-3'],
          isCheckpoint: false,
        },
        {
          lessonId: 'lesson-unity-8-5',
          order: 5,
          title: '8.5 - Фінальний реліз і портфоліо',
          learningObjectives: [],
          estimatedTime: 60,
          prerequisites: ['lesson-unity-8-4'],
          isCheckpoint: true,
        },
      ],
    },
  ],
}
