/**
 * SmartCode Roblox v2 — canonical lesson grid (92 lessons / 13 modules)
 */

export const COURSE_TITLE_UK =
  'Roblox Studio: від першої Part до власної гри'
export const COURSE_TITLE_EN =
  'Roblox Studio: From Your First Part to Your Own Game'

export const PHASES = [
  { id: 'A', titleUk: 'Студія і моделі', titleEn: 'Studio & Modeling', modules: [1, 2, 3] },
  { id: 'B', titleUk: 'Іскри з кодом', titleEn: 'Sparks & Ready Code', modules: [4] },
  { id: 'C', titleUk: 'Серйозний Lua', titleEn: 'Serious Lua', modules: [5, 6, 7, 8] },
  { id: 'D', titleUk: 'Ігрові механіки', titleEn: 'Game Mechanics', modules: [9, 10, 11, 12] },
  { id: 'E', titleUk: 'Реліз', titleEn: 'Release', modules: [13] },
]

export const MODULES = [
  {
    id: 1,
    weeks: 4,
    nameUk: 'Робочий стіл будівельника',
    nameEn: 'Builder Desk',
    taglineUk: 'Studio і Parts',
    taglineEn: 'Studio & Parts',
    descUk: 'Studio, Explorer, Parts, Properties, Snap — фундамент без скриптів. Артефакт: «Мій перший двір».',
    descEn: 'Studio, Explorer, Parts, Properties, Snap — foundations without scripts. Artifact: My First Yard.',
    outcomesUk: ['Орієнтуватися в Studio та Explorer', 'Створювати Parts з Anchored/CanCollide', 'Зібрати двір за чеклістом'],
    outcomesEn: ['Navigate Studio and Explorer', 'Create Parts with Anchored/CanCollide', 'Build a yard checklist-ready'],
    md: 'module-01-studio-builder.md',
    lessons: [
      ['Ласкаво просимо до Studio', 'Welcome to Studio'],
      ['Камера й перша доріжка', 'Camera and first path'],
      ['Explorer: порядок у світі', 'Explorer: world order'],
      ['Part і Properties', 'Parts and Properties'],
      ['Move, Scale, Rotate + Snap', 'Move, Scale, Rotate + Snap'],
      ['Будуємо двір: композиція', 'Building the yard: composition'],
      ['Workspace і Storage', 'Workspace and Storage'],
      ['Чекпоінт: Мій перший двір', 'Checkpoint: My first yard'],
    ],
  },
  {
    id: 2,
    weeks: 4,
    nameUk: 'Models, Union і будинок',
    nameEn: 'Models, Unions & House',
    taglineUk: 'Solid modeling',
    taglineEn: 'Solid modeling',
    descUk: 'Model vs Folder, PrimaryPart, Union/Negate, Decal. Артефакт: будинок з вікнами.',
    descEn: 'Model vs Folder, PrimaryPart, Union/Negate, Decals. Artifact: house with windows.',
    outcomesUk: ['Групувати Parts у Model', 'Різати отвори Negate+Union', 'Зібрати House з PrimaryPart'],
    outcomesEn: ['Group Parts into Models', 'Cut holes with Negate+Union', 'Assemble a House with PrimaryPart'],
    md: 'module-02-models-union.md',
    lessons: [
      ['Model чи Folder?', 'Model or Folder?'],
      ['PrimaryPart', 'PrimaryPart'],
      ['Union: зливаємо Parts', 'Union: merge Parts'],
      ['NegatePart: вирізаємо вікно', 'NegatePart: cut a window'],
      ['Separate і ремонт Union', 'Separate and repair Unions'],
      ['Pivot і збірка даху', 'Pivot and roof assembly'],
      ['Decal і фасад', 'Decals and facade'],
      ['Чекпоінт: будинок з вікнами', 'Checkpoint: house with windows'],
    ],
  },
  {
    id: 3,
    weeks: 3,
    nameUk: 'Світ, ландшафт і атмосфера',
    nameEn: 'World, Terrain & Atmosphere',
    taglineUk: 'Біом і світло',
    taglineEn: 'Biome & lighting',
    descUk: 'Terrain, Lighting, Sky, ambient-звук. Артефакт: живий біом навколо двору.',
    descEn: 'Terrain, Lighting, Sky, ambient sound. Artifact: a living biome around the yard.',
    outcomesUk: ['Малювати базовий terrain', 'Налаштувати Lighting/Sky', 'Додати ambient звук'],
    outcomesEn: ['Sculpt basic terrain', 'Tune Lighting/Sky', 'Add ambient sound'],
    md: 'module-03-world-atmosphere.md',
    lessons: [
      ['Terrain Editor: перша земля', 'Terrain Editor: first land'],
      ['Матеріали ландшафту і біом', 'Terrain materials and biome'],
      ['Lighting і Atmosphere', 'Lighting and Atmosphere'],
      ['Sky і листівка локації', 'Sky and location postcard'],
      ['Звук зони', 'Zone sound'],
      ['Чекпоінт: живий світ', 'Checkpoint: living world'],
    ],
  },
  {
    id: 4,
    weeks: 5,
    nameUk: 'Іскри: готовий код',
    nameEn: 'Sparks: Ready-Made Code',
    taglineUk: 'Перше «вау»',
    taglineEn: 'First wow',
    descUk: 'Output, шаблони Kill/CP/монети/двері/телепорт/меню. Артефакт: іскровий двір.',
    descEn: 'Output, Kill/CP/coins/doors/teleport/menu templates. Artifact: spark yard.',
    outcomesUk: ['Читати Output', 'Вставляти й кастомізувати шаблони', 'Зібрати 5+ механік у loop'],
    outcomesEn: ['Read the Output', 'Paste and customize templates', 'Combine 5+ mechanics into a loop'],
    md: 'module-04-sparks-ready-code.md',
    lessons: [
      ['Output, Script і print', 'Output, Script and print'],
      ['Kill brick (готовий Touched)', 'Kill brick (ready Touched)'],
      ['Checkpoint', 'Checkpoint'],
      ['Монета і leaderstats', 'Coins and leaderstats'],
      ['Двері на ClickDetector', 'Doors with ClickDetector'],
      ['Телепорт', 'Teleport'],
      ['Платформа що зникає', 'Fading platform'],
      ['Просте меню ScreenGui', 'Simple ScreenGui menu'],
      ['Збірка: Іскровий двір', 'Build: Spark yard'],
      ['Презентація: жива гра', 'Presentation: living game'],
    ],
  },
  {
    id: 5,
    weeks: 3,
    nameUk: 'Змінні та типи',
    nameEn: 'Variables and Types',
    taglineUk: 'Пишемо самі',
    taglineEn: 'We write it ourselves',
    descUk: 'local, number/string/boolean, Part через змінну, Vector3. Проєкт: Пульт кольору.',
    descEn: 'local, number/string/boolean, Part via variable, Vector3. Project: Color Console.',
    outcomesUk: ['Створювати local змінні', 'Змінювати Properties з коду', 'Зібрати Пульт кольору'],
    outcomesEn: ['Create local variables', 'Change Properties from code', 'Build the Color Console'],
    md: 'module-05-variables.md',
    lessons: [
      ['Що таке змінна', 'What is a variable'],
      ['Типи: number, string, boolean', 'Types: number, string, boolean'],
      ['Змінна вказує на Part', 'Variable points to a Part'],
      ['Числова логіка і рахунок', 'Number logic and score'],
      ['Vector3: розмір і позиція', 'Vector3: size and position'],
      ['Проєкт: Пульт кольору', 'Project: Color Console'],
    ],
  },
  {
    id: 6,
    weeks: 3,
    nameUk: 'Умови if / else',
    nameEn: 'Conditionals if / else',
    taglineUk: 'Рішення в коді',
    taglineEn: 'Decisions in code',
    descUk: 'Порівняння, if/elseif/else, Touched+умова, прапорці. Проєкт: VIP-двері.',
    descEn: 'Comparisons, if/elseif/else, Touched+condition, flags. Project: VIP doors.',
    outcomesUk: ['Писати порівняння і if', 'Фільтрувати Touched', 'Зробити toggle/VIP логіку'],
    outcomesEn: ['Write comparisons and if', 'Filter Touched events', 'Build toggle/VIP logic'],
    md: 'module-06-conditionals.md',
    lessons: [
      ['Порівняння і boolean', 'Comparisons and booleans'],
      ['if then end', 'if then end'],
      ['else і elseif', 'else and elseif'],
      ['Touched + if: зони', 'Touched + if: zones'],
      ['Прапорці і ClickDetector', 'Flags and ClickDetector'],
      ['Проєкт: двері VIP / пароль', 'Project: VIP / password doors'],
    ],
  },
  {
    id: 7,
    weeks: 3,
    nameUk: 'Цикли',
    nameEn: 'Loops',
    taglineUk: 'Повтори й фабрика',
    taglineEn: 'Repetition & factory',
    descUk: 'for, while, спавн Parts, таймер, цикл+if. Проєкт: Фабрика блоків.',
    descEn: 'for, while, Part spawn, timers, loop+if. Project: Brick Factory.',
    outcomesUk: ['Писати for і while', 'Спавнити Parts безпечно', 'Комбінувати цикл з if'],
    outcomesEn: ['Write for and while', 'Spawn Parts safely', 'Combine loops with if'],
    md: 'module-07-loops.md',
    lessons: [
      ['Навіщо цикли + for', 'Why loops + for'],
      ['for і спавн Part', 'for and Part spawn'],
      ['while і безпека', 'while and safety'],
      ['Таймер у грі', 'In-game timer'],
      ['Цикл + if: фільтр', 'Loop + if: filter'],
      ['Проєкт: Фабрика блоків', 'Project: Brick Factory'],
    ],
  },
  {
    id: 8,
    weeks: 4,
    nameUk: 'Функції, події, таблиці',
    nameEn: 'Functions, Events, Tables',
    taglineUk: 'Код як інструменти',
    taglineEn: 'Code as tools',
    descUk: 'function, параметри, return, Connect, ModuleScript, tables. Проєкт: інвентар + NPC.',
    descEn: 'function, params, return, Connect, ModuleScript, tables. Project: inventory + NPC.',
    outcomesUk: ['Писати функції з return', 'Підключати події іменовано', 'Використовувати таблиці й ModuleScript'],
    outcomesEn: ['Write functions with return', 'Wire named event handlers', 'Use tables and ModuleScripts'],
    md: 'module-08-functions-events-tables.md',
    lessons: [
      ['Що таке функція', 'What is a function'],
      ['Параметри', 'Parameters'],
      ['return', 'return'],
      ['Події: функція як реакція', 'Events: function as reaction'],
      ['ModuleScript intro', 'ModuleScript intro'],
      ['Таблиці: список', 'Tables: lists'],
      ['Словник + діалог NPC', 'Dictionaries + NPC dialog'],
      ['Проєкт: інвентар + NPC', 'Project: inventory + NPC'],
    ],
  },
  {
    id: 9,
    weeks: 4,
    nameUk: 'Obby / платформер',
    nameEn: 'Obby / Platformer',
    taglineUk: 'Рівень своїм кодом',
    taglineEn: 'Level with your code',
    descUk: 'Дизайн маршруту, пастки-системою, CP, movers, фініш, таймер. Здача run.',
    descEn: 'Course design, hazard systems, CPs, movers, finish, timer. Submit a full run.',
    outcomesUk: ['Зібрати playable obby', 'Масштабувати пастки функціями', 'Додати фініш і таймер'],
    outcomesEn: ['Ship a playable obby', 'Scale hazards with functions', 'Add finish and timer'],
    md: 'module-09-obby.md',
    lessons: [
      ['Дизайн маршруту obby', 'Obby route design'],
      ['Пастки функціями', 'Hazards with functions'],
      ['Чекпоінти системою', 'Checkpoint system'],
      ['Рухомі платформи', 'Moving platforms'],
      ['Фініш і перемога', 'Finish and victory'],
      ['Таймер проходження', 'Run timer'],
      ['Баланс і polish', 'Balance and polish'],
      ['Чекпоінт: презентація Obby', 'Checkpoint: Obby presentation'],
    ],
  },
  {
    id: 10,
    weeks: 3,
    nameUk: 'Симулятор',
    nameEn: 'Simulator',
    taglineUk: 'Прогресія чисел',
    taglineEn: 'Number progression',
    descUk: 'Збір, Power, магазин, RemoteEvent GUI, мета. Артефакт: міні-симулятор.',
    descEn: 'Collecting, Power, shop, RemoteEvent GUI, goals. Artifact: mini-simulator.',
    outcomesUk: ['Звʼязати збір і Power', 'Зробити серверні покупки', 'Збалансувати сесію'],
    outcomesEn: ['Link collecting and Power', 'Ship server-side purchases', 'Balance a session'],
    md: 'module-10-simulator.md',
    lessons: [
      ['Ядро жанру симулятора', 'Simulator genre core'],
      ['Збір і Power', 'Collecting and Power'],
      ['Магазин: ціни і canAfford', 'Shop: prices and canAfford'],
      ['UI магазину + RemoteEvent', 'Shop UI + RemoteEvent'],
      ['Множник і мета', 'Multiplier and goal'],
      ['Чекпоінт: презентація симулятора', 'Checkpoint: simulator presentation'],
    ],
  },
  {
    id: 11,
    weeks: 4,
    nameUk: 'Tycoon',
    nameEn: 'Tycoon',
    taglineUk: 'База і економіка',
    taglineEn: 'Base & economy',
    descUk: 'Plot, dropper, collector, кнопки, апгрейди, rebirth, save lite.',
    descEn: 'Plot, dropper, collector, buttons, upgrades, rebirth, light save.',
    outcomesUk: ['Побудувати drop→collect→cash', 'Робити покупки на plot', 'Додати rebirth або save'],
    outcomesEn: ['Build drop→collect→cash', 'Run plot purchases', 'Add rebirth or save'],
    md: 'module-11-tycoon.md',
    lessons: [
      ['Plot: моя база', 'Plot: my base'],
      ['Dropper', 'Dropper'],
      ['Collector', 'Collector'],
      ['Кнопки покупок', 'Purchase buttons'],
      ['Апгрейди доходу', 'Income upgrades'],
      ['Rebirth lite', 'Rebirth lite'],
      ['Збереження прогресу', 'Saving progress'],
      ['Чекпоінт: презентація Tycoon', 'Checkpoint: Tycoon presentation'],
    ],
  },
  {
    id: 12,
    weeks: 3,
    nameUk: 'Tools і GUI',
    nameEn: 'Tools & GUI',
    taglineUk: 'Інструменти в руках',
    taglineEn: 'Tools in hand',
    descUk: 'Tool → урон → HP UI + магазин → арена з juice → здача.',
    descEn: 'Tool → damage → HP UI + shop → juiced arena → checkpoint.',
    outcomesUk: ['Створити Tool з дією', 'Показати HP у GUI', 'Продати Tool через whitelist'],
    outcomesEn: ['Create a Tool with an action', 'Show HP in GUI', 'Sell Tools via whitelist'],
    md: 'module-12-tools-gui.md',
    lessons: [
      ['Що таке Tool', 'What is a Tool'],
      ['Activated: інструмент діє', 'Activated: tool acts'],
      ['Урон і Humanoid', 'Damage and Humanoid'],
      ['GUI HP + магазин Tools', 'HP GUI + Tools shop'],
      ['Збірка арени + juice', 'Arena build + juice'],
      ['Чекпоінт: презентація Tools', 'Checkpoint: Tools presentation'],
    ],
  },
  {
    id: 13,
    weeks: 3,
    nameUk: 'Реліз і Showcase',
    nameEn: 'Release & Showcase',
    taglineUk: 'Доводимо до кінця',
    taglineEn: 'Ship it',
    descUk: 'Пітч, vertical slice, Must, UX, publish+буст lite, freeze+Showcase Day.',
    descEn: 'Pitch, vertical slice, Must, UX, publish+boost lite, freeze+Showcase Day.',
    outcomesUk: ['Довести гру до v1', 'Пройти UX-чекліст', 'Презентувати на Showcase'],
    outcomesEn: ['Ship a v1 game', 'Pass a UX checklist', 'Present on Showcase Day'],
    md: 'module-13-release.md',
    lessons: [
      ['Пітч і вибір жанру', 'Pitch and genre pick'],
      ['Vertical slice', 'Vertical slice'],
      ['Must #2 і #3', 'Must #2 and #3'],
      ['Багфікс і UX-прохід', 'Bugfix and UX pass'],
      ['Publish + GamePass/Badge lite', 'Publish + GamePass/Badge lite'],
      ['Feature freeze + Showcase Day', 'Feature freeze + Showcase Day'],
    ],
  },
]

export function flattenLessons() {
  const out = []
  for (const mod of MODULES) {
    mod.lessons.forEach(([titleUk, titleEn], i) => {
      const lessonNum = i + 1
      const isCheckpoint =
        /чекпоінт|checkpoint|showcase|презентація|presentation|проєкт:|project:/i.test(
          titleUk
        ) || lessonNum === mod.lessons.length
      out.push({
        moduleId: `module-${String(mod.id).padStart(2, '0')}`,
        moduleNum: mod.id,
        lessonNum,
        lessonId: `lesson-roblox-${mod.id}-${lessonNum}`,
        titleUk: `${mod.id}.${lessonNum} — ${titleUk}`,
        titleEn: `${mod.id}.${lessonNum} — ${titleEn}`,
        shortTitleUk: titleUk,
        shortTitleEn: titleEn,
        isCheckpoint,
        weeks: mod.weeks,
        module: mod,
      })
    })
  }
  return out
}
